copy /Y "d:\Work\Log\Release\Log.lib" "x86\Log.lib"
copy /Y "d:\Work\Log\Debug\Log.lib" "x86\Logd.lib"
copy /Y "d:\Work\Log\x64\Release\Log.lib" "x64\Log.lib"
copy /Y "d:\Work\Log\x64\Debug\Log.lib" "x64\Logd.lib"
copy /Y "d:\Work\Log\Log\Include\*.h" "Include\"